[package]
name = "twitter_arg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"
rand = "0.9.0-alpha.1"
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros"] }
